#!/bin/bash
#  for-loopcmd.sh: for-loop with [list]
#+ generated by command substitution.

NUMBERS="9 7 3 8 37.53"
count=1

echo "====="

for number in $NUMBERS  # for number in 9 7 3 8 37.53
do
  echo "count=$count"
  echo "number=$number"
  (( count++ ))
  echo "-----"
done

echo 
exit 0
